
@baseUrl = http://localhost:3000

############
### Time ###
############

# @name timesNew
POST {{baseUrl}}/times HTTP/1.1
content-type: application/json

{
    "name": "Super Mario World",
    "description": "Super Nintendo Top"
}
###
GET {{baseUrl}}/times HTTP/1.1
###
GET {{baseUrl}}/times/1 HTTP/1.1
###
PUT {{baseUrl}}/times/1 HTTP/1.1
content-type: application/json

{
    "name": "Super Mario 222",
    "description": "Super Nintendo"
}
###
DELETE {{baseUrl}}/times/2 HTTP/1.1
###

###############
### Players ###
###############

# @name playersNew
POST {{baseUrl}}/times/1/players HTTP/1.1
content-type: application/json

{
    "name": "Super Mario World",
    "latname": "Super Nintendo",
    "nick": "Juca",
    "role": "Player",
    "id_time": 1
}

GET {{baseUrl}}/times/1/players HTTP/1.1
###
GET {{baseUrl}}/times/1/players/1 HTTP/1.1
###
PUT {{baseUrl}}/times/1/players/1 HTTP/1.1
content-type: application/json

{
    "name": "Zé",
    "latname": "Claudio",
    "nick": "storn",
    "role": "Player",
    "id_time": 1
}

###
DELETE {{baseUrl}}/times/1/players/2 HTTP/1.1
###